apiVersion: v1
kind: Service
metadata:
  name: watchdog-client
spec:
  type: LoadBalancer
  ports:
  - port: 5025
    targetPort: 80
  selector:
    web-client: watchdog-client

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: watchdog-client
spec:
  selector:
    matchLabels:
      web-client: watchdog-client
  template:
    metadata:
      labels:
        web-client: watchdog-client
        system: client
    spec:
      containers:
      - name: watchdog-client
        image: dockerlakov/myonlineshop-watchdog:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "250m"
        env:
        - name: HealthChecks-UI__HealthChecks__0__Name
          value: Catalog
        - name: HealthChecks-UI__HealthChecks__0__Uri
          valueFrom:
            configMapKeyRef:
              name: environment-settings
              key: watchdog-catalog-health
        - name: HealthChecks-UI__HealthChecks__1__Name
          value: Identity
        - name: HealthChecks-UI__HealthChecks__1__Uri
          valueFrom:
            configMapKeyRef:
              name: environment-settings
              key: watchdog-identity-health
        - name: HealthChecks-UI__HealthChecks__2__Name
          value: Statistics
        - name: HealthChecks-UI__HealthChecks__2__Uri
          valueFrom:
            configMapKeyRef:
              name: environment-settings
              key: watchdog-statistics-health
        - name: HealthChecks-UI__HealthChecks__3__Name
          value: Ordering
        - name: HealthChecks-UI__HealthChecks__3__Uri
          valueFrom:
            configMapKeyRef:
              name: environment-settings
              key: watchdog-ordering-health
        - name: HealthChecks-UI__HealthChecks__4__Name
          value: Shoppingcart
        - name: HealthChecks-UI__HealthChecks__4__Uri
          valueFrom:
            configMapKeyRef:
              name: environment-settings
              key: watchdog-shoppingcart-health
